apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: tekton-triggers-role
rules:
  - apiGroups: ["tekton.dev"]
    resources: ["eventlisteners", "triggerbindings", "triggertemplates", "tasks", "taskruns"]
    verbs: ["get"]
  - apiGroups: [""]
    resources: ["configmaps", "secrets"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["tekton.dev"]
    resources: ["pipelineruns", "pipelineresources", "taskruns"]
    verbs: ["create"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tekton-triggers-serviceaccount
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tekton-triggers-rolebinding
subjects:
  - kind: ServiceAccount
    name: tekton-triggers-serviceaccount
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: tekton-triggers-role
---
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-secret
stringData:
  secret: foobar
---
apiVersion: tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: pipeline-binding
spec:
  params:
    - name: gitrevision
      value: $(body.head_commit.id)
    - name: gitrepourl
      value: $(body.repository.git_url)
    - name: reponame
      value: $(body.repository.name)
---
apiVersion: tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: pipeline-template
spec:
  params:
    - name: gitrevision
      description: The git revision
      default: master
    - name: gitrepourl
      description: The git repository url
    - name: reponame
      description: The git repo name
  resourcetemplates:
    - apiVersion: tekton.dev/v1alpha1
      kind: PipelineRun
      metadata:
        name: test-build-deploy-pipeline-run-$(uid)
      spec:
        pipelineRef:
          name: test-build-deploy-pipeline
        serviceAccountName: kn-deployer-account
        podTemplate:
          volumes:
            - name: my-cache
              persistentVolumeClaim:
                claimName: my-volume-claim
        resources:
          - name: source
            resourceSpec:
              type: git
              params:
                - name: revision
                  value: $(params.gitrevision)
                - name: url
                  value: $(params.gitrepourl)
          - name: image
            resourceSpec:
              type: image
              params:
                - name: url
                  value: gcr.io/jw-demo/$(params.reponame)
        params:
          - name: service-name
            value: $(params.reponame)
---
apiVersion: tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: github-listener
spec:
  serviceAccountName: tekton-triggers-serviceaccount
  triggers:
    - name: trigger
      interceptors:
        - github:
            secretRef:
              secretName: github-webhook-secret
              secretKey: secret
            eventTypes:
              - push
      bindings:
        - name: pipeline-binding
      template:
        name: pipeline-template
---
apiVersion: v1
kind: Service
metadata:
  name: el-github-listener-loadbalancer
spec:
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  ports:
    - port: 80
      targetPort: 8080
  selector:
    eventlistener: github-listener
