apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: tekton-triggers-admin
rules:
  - apiGroups:
      - triggers.tekton.dev
    resources:
      - eventlisteners
      - triggerbindings
      - triggertemplates
    verbs:
      - get
  - apiGroups:
      - tekton.dev
    resources:
      - pipelineruns
      - pipelineresources
    verbs:
      - create
  - apiGroups:
      - ""
    resources:
      - configmaps
      - secrets
    verbs:
      - get
      - list
      - watch
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tekton-triggers-admin
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tekton-triggers-admin-binding
subjects:
  - kind: ServiceAccount
    name: tekton-triggers-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: tekton-triggers-admin
---
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-secret
stringData:
  secret: foobar
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: pipeline-binding
spec:
  params:
    - name: gitrevision
      value: $(body.head_commit.id)
    - name: gitrepourl
      value: $(body.repository.git_url)
    - name: reponame
      value: $(body.repository.name)
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: pipeline-template
spec:
  params:
    - name: gitrevision
      description: The git revision
      default: master
    - name: gitrepourl
      description: The git repository url
    - name: reponame
      description: The git repo name
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        name: build-deploy-pipeline-run-$(uid)
      spec:
        pipelineRef:
          name: build-deploy-pipeline
        serviceAccountName: kn-deployer-account
        resources:
          - name: image
            resourceSpec:
              type: image
              params:
                - name: url
                  value: gcr.io/jw-demo/$(tt.params.reponame)
        params:
          - name: service-name
            value: $(tt.params.reponame)
          - name: git-url
            value: $(tt.params.gitrepourl)
          - name: git-branch
            value: $(tt.params.gitrevision)
          - name: image-url
            value: gcr.io/jw-demo/$(tt.params.reponame)
        workspaces:
          - name: source
            volumeClaimTemplate:
              spec:
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 1Gi
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: github-listener
spec:
  serviceAccountName: tekton-triggers-admin
  triggers:
    - name: trigger
      interceptors:
        - github:
            secretRef:
              secretName: github-webhook-secret
              secretKey: secret
            eventTypes:
              - push
      bindings:
        - ref: pipeline-binding
      template:
        name: pipeline-template
---
apiVersion: v1
kind: Service
metadata:
  name: el-github-listener-loadbalancer
spec:
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  ports:
    - port: 80
      targetPort: 8080
  selector:
    eventlistener: github-listener
